export const categories = [
	{id: 0, name: 'EKO', img: require('../assets/categories/eko.png')},
	{id: 1, name: 'SLODYCZE', img: require('../assets/categories/slodycze.png')},
	{id: 2, name: 'KALENDARZE', img: require('../assets/categories/kalendarze.png')},
	{id: 3, name: 'KUBKI', img: require('../assets/categories/kubki.png')},
	{id: 4, name: 'PENDRIVE', img: require('../assets/categories/pendrive.png')},
	{id: 5, name: 'TORBY', img: require('../assets/categories/torby.png')},
	{id: 6, name: 'SMYCZE', img: require('../assets/categories/smycze.png')},
	{id: 7, name: 'DLA DZIECI', img: require('../assets/categories/dla_dzieci.png')},
	{id: 8, name: 'CZAPKI', img: require('../assets/categories/czapki.png')},
	{id: 9, name: 'DO BIURA', img: require('../assets/categories/do_biura.png')},
	{id: 10, name: 'ELEKTRONIKA', img: require('../assets/categories/elektronika.png')},
	{id: 11, name: 'PARASOLE', img: require('../assets/categories/parasole.png')},
	{id: 12, name: 'KOSZULKI', img: require('../assets/categories/koszulki.png')},
	{id: 13, name: 'BRELOKI', img: require('../assets/categories/breloki.png')},
	{id: 14, name: 'NARZEDZIA', img: require('../assets/categories/narzedzia.png')},
	{id: 15, name: 'POLIGRAFIA', img: require('../assets/categories/poligrafia.png')},
	{id: 16, name: 'WYPOCZYNEK', img: require('../assets/categories/wypoczynek.png')},
	{id: 17, name: 'PLAZOWANIE', img: require('../assets/categories/plazowanie.png')},
	{id: 18, name: 'ROWEROWE', img: require('../assets/categories/rowerowe.png')},
	{id: 19, name: 'HAMAKI', img: require('../assets/categories/hamaki.png')},
	{id: 20, name: 'LEZAKI', img: require('../assets/categories/lezaki.png')},
];
