export const categories = [
	{id: 0, name: 'EKO', img: require('../assets/icons/eko.png')},
	{id: 1, name: 'SLODYCZE', img: require('../assets/icons/slodycze.png')},
	{id: 2, name: 'KALENDARZE', img: require('../assets/icons/kalendarze.png')},
	{id: 3, name: 'KUBKI', img: require('../assets/icons/kubki.png')},
	{id: 4, name: 'PENDRIVE', img: require('../assets/icons/pendrive.png')},
	{id: 5, name: 'TORBY', img: require('../assets/icons/torby.png')},
	{id: 6, name: 'SMYCZE', img: require('../assets/icons/smycze.png')},
	{id: 7, name: 'DLA DZIECI', img: require('../assets/icons/dla_dzieci.png')},
	{id: 8, name: 'CZAPKI', img: require('../assets/icons/czapki.png')},
	{id: 9, name: 'DO BIURA', img: require('../assets/icons/do_biura.png')},
	{id: 10, name: 'ELEKTRONIKA', img: require('../assets/icons/elektronika.png')},
	{id: 11, name: 'PARASOLE', img: require('../assets/icons/parasole.png')},
	{id: 12, name: 'KOSZULKI', img: require('../assets/icons/koszulki.png')},
	{id: 13, name: 'BRELOKI', img: require('../assets/icons/breloki.png')},
	{id: 14, name: 'NARZEDZIA', img: require('../assets/icons/narzedzia.png')},
	{id: 15, name: 'POLIGRAFIA', img: require('../assets/icons/poligrafia.png')},
	{id: 16, name: 'WYPOCZYNEK', img: require('../assets/icons/wypoczynek.png')},
	{id: 17, name: 'PLAZOWANIE', img: require('../assets/icons/plazowanie.png')},
	{id: 18, name: 'ROWEROWE', img: require('../assets/icons/rowerowe.png')},
	{id: 19, name: 'HAMAKI', img: require('../assets/icons/hamaki.png')},
	{id: 20, name: 'LEZAKI', img: require('../assets/icons/lezaki.png')},
];
