export const categories = [
	{id: 0, name: 'EKO', img: require('../assets/eko.png')},
	{id: 1, name: 'SLODYCZE', img: require('../assets/slodycze.png')},
	{id: 2, name: 'KALENDARZE', img: require('../assets/kalendarze.png')},
	{id: 3, name: 'KUBKI', img: require('../assets/kubki.png')},
	{id: 4, name: 'PENDRIVE', img: require('../assets/pendrive.png')},
	{id: 5, name: 'TORBY', img: require('../assets/torby.png')},
	{id: 6, name: 'SMYCZE', img: require('../assets/smycze.png')},
	{id: 7, name: 'DLA DZIECI', img: require('../assets/dla_dzieci.png')},
	{id: 8, name: 'CZAPKI', img: require('../assets/czapki.png')},
	{id: 9, name: 'DO BIURA', img: require('../assets/do_biura.png')},
	{id: 10, name: 'ELEKTRONIKA', img: require('../assets/elektronika.png')},
	{id: 11, name: 'PARASOLE', img: require('../assets/parasole.png')},
	{id: 12, name: 'KOSZULKI', img: require('../assets/koszulki.png')},
	{id: 13, name: 'BRELOKI', img: require('../assets/breloki.png')},
	{id: 14, name: 'NARZEDZIA', img: require('../assets/narzedzia.png')},
	{id: 15, name: 'POLIGRAFIA', img: require('../assets/poligrafia.png')},
	{id: 16, name: 'WYPOCZYNEK', img: require('../assets/wypoczynek.png')},
	{id: 17, name: 'PLAZOWANIE', img: require('../assets/plazowanie.png')},
	{id: 18, name: 'ROWEROWE', img: require('../assets/rowerowe.png')},
	{id: 19, name: 'HAMAKI', img: require('../assets/hamaki.png')},
	{id: 20, name: 'LEZAKI', img: require('../assets/lezaki.png')},
];
