export const offers = [
	{
		id: 1,
		name: 'Oferta gadżetów',
		subcategories: [
			'Do biura',
			'VIP',
			'Do domu',
			'Narzędzia',
			'Na targi i konferencje',
			'Wypoczynek',
			'Torby, walizki, plecaki',
			'Tekstylia i Odzież',
			'Parasole',
			'Elektronika',
			'Poligrafia',
			'Dla dzieci',
			'Inne',
			'Gadżety świąteczne',
		],
	},
	{
		id: 2,
		name: 'Oferta tematyczna',
		subcategories: [
			'Nasze Bestsellery',
			'Gadżety markowe',
			'Odzież reklamowa',
			'Nowości',
			'Gadżety reklamowe ekologiczne',
			'Gadżety reklamowe wyborcze',
			'Gadżety reklamowe dla biur nieruchomości',
			'Inspiracje',
			'Gadżety do 1 zł',
		],
	},
	{
		id: 3,
		name: 'Rabaty i promocje',
		subcategories: [
			'Produkty w niższych cenach',
			'Promocja miesiąca',
			'Prezent dla pracownika',
			'Prezenty dla firm',
			'Giftbox',
			'Archiwalne promocje',
		],
	},
];
